### PR TITLE
 port from cljx to cljc #30 

### PR DESCRIPTION
**Pull request by achengs**
$ lein test
    
    lein test automat.core-simple-check
    
    lein test automat.core-test
    
    lein test automat.fsm-simple-check
    {:result true, :num-tests 100, :seed 1452730787652, :test-var check-closed-over-operations}
    
    lein test automat.fsm-test
    
    Ran 5 tests containing 37 assertions.
    0 failures, 0 errors.

### CODE REVIEW

**Comment by achengs** [comment]
`lein clean-build && lein test && lein cljsbuild test` gets as far as attempting to test with `phantomjs` in my environment... which fails because `phantom` fails to build from source on my machine.  I have `Leiningen 2.5.3 on Java 1.8.0_45 Java HotSpot(TM) 64-Bit Server VM` and I see warnings up to that point, not failures. The build on Travis CI encounters a failure earlier in the process.

**Comment by ztellman** [comment]
I'm sorry that I can't be more help here, I haven't used CLJS enough to understand what might be going wrong.

**Comment by achengs** [comment]
A build passed! But how to trigger another build to check [3db926f](https://github.com/achengs/automat/commit/3db926f4a87e85bbbf255a7e6203ef80c68ff666) ?

**Comment by achengs** [comment]
Woah. The build passes even with ClassNotFoundExceptions. Trying to fix now...

**Pull request closed without merging**
