### PR TITLE
Delay cljs.compiler/emit-constant registration until CLJS compile-time

### LINKED ISSUE #68: Using AOT with clojurescript dependency throws ClassCastException
Hi @ztellman just updating this problem in a clean and separate issue 

### Description 
+ adding `org.clojure/clojurescript` dependency and `:aot :all` with `ztellman/automat` throws error when executing standalone jar
` Caused by: java.lang.ClassCastException: clojure.lang.Var$Unbound cannot be cast to clojure.lang.MultiFn`

### example code
https://github.com/tangrammer/automat-issue

### PR DESCRIPTION
**Pull request by cemerick**
fixes #68

### CODE REVIEW

**Comment by ztellman** [comment]
Great, thank you.  Would you like me to cut a release with this fix?

**Comment by cemerick** [comment]
Ah, sure, that'd be great. I have an artifact up for people to test, but it's really a pretty straightforward change. (Though I have some theories, **why** the change is needed is a complete mystery to me.)

**Comment by cemerick** [comment]
FYI, I believe the first release where this became a problem is CLJS `1.9.671`. The prior approach was fine with AOT for earlier releases; the suggested change should be good for approximately any 1.9.x release.

**Comment by cemerick** [comment]
Hold up on a release. This doesn't play nicely with CLJS advanced optimizations.

**Comment by tangrammer** [comment]
Hi there :) 
any progress related with the advanced optimizations ... @cemerick  maybe you want to extend here the details of your current path?

**Comment by cemerick** [comment]
#70 resolves the problem entirely, just needs merging. Been using the result of that for a couple of weeks now with good results.

**Comment by tangrammer** [comment]
Great, thanks a lot!

**Comment by ztellman** [comment]
Sorry for the delay, I've merged the change and cut a new release

**Pull request merged**
